pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t nodejs-cloud-app .'
            }
        }
        
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        
        stage('Deploy') {
            steps {
                sh './scripts/deploy.sh'
            }
        }
    }
}